/*
 * URL of the live JSON file generated by the mod jc_special.
 */
const SERVER_JSON_URL = "https://game.dssapp.us/justcraft/server.json";

/*
 * Website translations.
 *
 * For now, we use hard coded words until I figure out
 * a better way to offer a translated website with
 * GitHub hosting.
 *
 * English is the fallback language.
 */
const translations = {
  en: {
    pageTitle: "Just-Craft Adventure | Official Server",
    serverTitle: "JUST-CRAFT ADVENTURE SERVER",
    officialCommunity: "Official Community",
    joinDiscord: "Join our Discord!",
    joinLink: "JOIN",
    officialForum: "Luanti Forum",
    visitForum: "Just-Craft Forum Post",
    visitLink: "VISIT",
    liveServerStatus: "LIVE SERVER STATUS",
    checkingServer: "Checking server...",
    serverOnline: "SERVER ONLINE",
    serverStatusUnavailable: "SERVER STATUS UNAVAILABLE",
    playersOnline: "PLAYERS ONLINE",
    totalMods: "TOTAL NUMBER OF MODS",
    luantiVersion: "LUANTI VERSION",
    onlinePlayers: "ONLINE PLAYERS",
    checkingPlayers: "Checking players...",
    nobodyOnline: "Nobody is currently online.",
    serverPlaces: "SERVER PLACES",
    loadingRules: "Loading server rules...",
    serverRulesTitle: "SERVER RULES",
    noRules: "No server rules are currently available.",
    couldNotContact: "Could not contact the server.",
    serverDataUpdated: "Server data updated: ",
    footerPowered: "Powered by Luanti."
  },

  es: {
    pageTitle: "Just-Craft Adventure | Servidor Oficial",
    serverTitle: "SERVIDOR JUST-CRAFT ADVENTURE",
    officialCommunity: "Comunidad Oficial",
    joinDiscord: "¡Únete a nuestro Discord!",
    joinLink: "UNIRSE",
    officialForum: "Foro de Luanti",
    visitForum: "Publicación del foro de Just-Craft",
    visitLink: "VISITAR",
    liveServerStatus: "ESTADO DEL SERVIDOR EN VIVO",
    checkingServer: "Comprobando servidor...",
    serverOnline: "SERVIDOR EN LÍNEA",
    serverStatusUnavailable: "ESTADO DEL SERVIDOR NO DISPONIBLE",
    playersOnline: "JUGADORES EN LÍNEA",
    totalMods: "NÚMERO TOTAL DE MODS",
    luantiVersion: "VERSIÓN DE LUANTI",
    onlinePlayers: "JUGADORES EN LÍNEA",
    checkingPlayers: "Comprobando jugadores...",
    nobodyOnline: "Nadie está conectado actualmente.",
    serverPlaces: "LUGARES DEL SERVIDOR",
    serverRulesTitle: "REGLAS DEL SERVIDOR",
    loadingRules: "Cargando las reglas del servidor...",
    noRules: "No hay reglas del servidor disponibles actualmente.",
    couldNotContact: "No se pudo contactar con el servidor.",
    serverDataUpdated: "Datos del servidor actualizados: ",
    footerPowered: "Desarrollado con Luanti."
  }
};

/*
 * Detect visitor language.
 *
 * Spanish browsers use Spanish.
 * Everything else uses English.
 */
const browserLanguage = navigator.language.toLowerCase();

const currentLanguage = browserLanguage.startsWith("es") ? "es" : "en";
// const currentLanguage = "es";

/*
 * Set the HTML language.
 */
document.documentElement.lang = currentLanguage;

const T = translations[currentLanguage];

/*
 * Apply website translations.
 */
function applyTranslations(){
  document.title = T.pageTitle;

  document.getElementById("serverTitle").textContent = T.serverTitle;

  document.getElementById("officialCommunity").textContent = T.officialCommunity;
  document.getElementById("joinDiscord").textContent = T.joinDiscord;
  document.getElementById("joinLink").textContent = T.joinLink;

  document.getElementById("officialForum").textContent = T.officialForum;
  document.getElementById("visitForum").textContent = T.visitForum;
  document.getElementById("visitLink").textContent = T.visitLink;

  document.getElementById("liveServerStatus").textContent = T.liveServerStatus;

  document.getElementById("playersOnlineLabel").textContent = T.playersOnline;
  document.getElementById("totalModsLabel").textContent = T.totalMods;
  document.getElementById("luantiVersionLabel").textContent = T.luantiVersion;

  document.getElementById("onlinePlayersTitle").textContent = T.onlinePlayers;
  document.getElementById("serverPlacesTitle").textContent = T.serverPlaces;

  document.getElementById("serverRulesTitle").textContent = T.serverRulesTitle;

  document.getElementById("loadingRules").textContent = T.loadingRules;

  document.getElementById("footerPowered").textContent = T.footerPowered;
}

/*
 * Load server information.
 */
async function loadServerData(){
  try{
    /*
     * Add a timestamp to prevent browser caching.
     */
    const response = await fetch(SERVER_JSON_URL + "?t=" + Date.now(), { cache: "no-store" } );

    if(!response.ok){
      throw new Error( "HTTP error: " + response.status );
    }

    const data = await response.json();
    // const rules = currentLanguage === "es" ? data.rules_es : data.rules;
    const rules = (currentLanguage === "es")
      ? (data.rules_es ? data.rules_es : data.rules)
      : (data.rules ? data.rules : null);

    /*
     * Server is online.
     */
    document.getElementById("statusDot").className = "status-dot online";
    document.getElementById("serverStatus").textContent = T.serverOnline;

    /*
     * Player counts.
     */
    document.getElementById("onlinePlayers").textContent = data.players.online;

    /*
     * Mod counts.
     */
    document.getElementById("totalModCount").textContent = data.server.mods.toLocaleString();

    /*
     * Luanti version.
     */

    document.getElementById("luantiVersion").textContent = data.server.luanti_version;

    /*
     * Online player names.
     */
    const playerList = document.getElementById("playerList");
    playerList.innerHTML = "";

    if(data.players.online_names && data.players.online_names.length > 0){
      data.players.online_names.forEach(
        function(playerName){
          const player = document.createElement("span");
          player.className = "player-name";
          player.textContent = playerName;
          playerList.appendChild(player);
        }
      );
    }else{
      playerList.innerHTML = '<span class="no-players">' + T.nobodyOnline + '</span>';
    }

    /*
     * Server places.
     */
    const placesList = document.getElementById("placesList");
    placesList.innerHTML = "";
    if(data.places){
      data.places.forEach(
        function(place){
          const card = document.createElement("div");
          card.className = "place-card";

          card.innerHTML =
            '<div class="place-name">' +
              place.label +
            '</div>' +
            '<div class="place-command">' +
              '/' +
              place.name +
            '</div>' +
            '<div class="place-coordinates">' +
              '(' + place.x + ',' + place.y + ',' + place.z + ')' +
            '</div>'  +
            '';
          placesList.appendChild(card);
        }
      );
    }

    /*
     * Server rules.
     */
    const rulesList = document.getElementById("rulesList");
    rulesList.innerHTML = "";

    if(rules && rules.length > 0){
      rules.forEach(
        function(rule, index){
          const ruleItem = document.createElement("div");
          ruleItem.className = "rule-item";

          const ruleNumber = document.createElement("span");
          ruleNumber.className = "rule-number";
          ruleNumber.textContent = (index + 1) + ")";

          ruleItem.appendChild(ruleNumber);
          ruleItem.appendChild(document.createTextNode(rule));

          rulesList.appendChild(ruleItem);
        }
      );

    }else{
      rulesList.innerHTML = '<div class="no-players">' + T.noRules + '</div>';
    }

    /*
     * Last update time.
     */
    const updatedDate = new Date(data.updated);

    const year = updatedDate.getFullYear();
    const month = String(updatedDate.getMonth() + 1).padStart(2, "0");
    const day = String(updatedDate.getDate()).padStart(2, "0");
    const hours = String(updatedDate.getHours()).padStart(2, "0");
    const minutes = String(updatedDate.getMinutes()).padStart(2, "0");

    const formattedDate = year + "-" + month + "-" + day + " " + hours + ":" + minutes;

    document .getElementById("updatedTime").textContent = T.serverDataUpdated + formattedDate;
  }catch(error){
    /*
     * Server appears offline or unreachable.
     */
    console.error("Could not load server data:", error);
    document.getElementById("statusDot").className = "status-dot offline";
    document.getElementById("serverStatus").textContent = T.serverStatusUnavailable;
    document.getElementById("playerList").innerHTML = '<span class="no-players">' + T.couldNotContact + '</span>';
  }
}

/*
 * Apply translations.
 */
applyTranslations();

/*
 * Load immediately.
 */
loadServerData();

/*
 * Refresh every 60 seconds.
 */
setInterval(loadServerData, 60000);