/*
 * URL of the live JSON file generated by jc_special.
 */
const SERVER_JSON_URL = "https://game.dssapp.us/justcraft/server.json";

/*
 * Load server information.
 */
async function loadServerData(){
  try{
    /*
     * Add a timestamp to prevent browser caching.
     */
    const response = await fetch(SERVER_JSON_URL + "?t=" + Date.now(), { cache: "no-store" } );

    if(!response.ok){
      throw new Error( "HTTP error: " + response.status );
    }

    const data = await response.json();

    /*
     * Server is online.
     */
    document.getElementById("statusDot").className = "status-dot online";
    document.getElementById("serverStatus").textContent = "SERVER ONLINE";

    /*
     * Player counts.
     */
    document.getElementById("onlinePlayers").textContent = data.players.online;

    /*
     * Mod counts.
     */
    document.getElementById("totalModCount").textContent = data.server.mods.toLocaleString();

    /*
     * Luanti version.
     */

    document.getElementById("luantiVersion").textContent = data.server.luanti_version;

    /*
     * Online player names.
     */
    const playerList = document.getElementById("playerList");
    playerList.innerHTML = "";

    if(data.players.online_names && data.players.online_names.length > 0){
      data.players.online_names.forEach(
        function(playerName){
          const player = document.createElement("span");
          player.className = "player-name";
          player.textContent = playerName;
          playerList.appendChild(player);
        }
      );

    }else{
      playerList.innerHTML = '<span class="no-players">' + 'Nobody is currently online.' + '</span>';
    }


    /*
     * Server places.
     */
    const placesList = document.getElementById("placesList");
    placesList.innerHTML = "";
    if(data.places){
      data.places.forEach(
        function(place){
          const card = document.createElement("div");
          card.className = "place-card";

          card.innerHTML =
            '<div class="place-name">' +
              place.label +
            '</div>' +
            '<div class="place-command">' +
              '/' +
              place.name +
            '</div>' +
            '<div class="place-coordinates">' +
              '(' + place.x + ',' + place.y + ',' + place.z + ')' +
            '</div>'  +
            '';
          placesList.appendChild(card);
        }
      );
    }

    /*
     * Server rules.
     */
    const rulesList = document.getElementById("rulesList");
    rulesList.innerHTML = "";

    if(data.rules && data.rules.length > 0){
      data.rules.forEach(
        function(rule, index){
          const ruleItem = document.createElement("div");
          ruleItem.className = "rule-item";

          const ruleNumber = document.createElement("span");
          ruleNumber.className = "rule-number";
          ruleNumber.textContent = (index + 1) + ")";

          ruleItem.appendChild(ruleNumber);
          ruleItem.appendChild(document.createTextNode(rule));

          rulesList.appendChild(ruleItem);
        }
      );

    }else{
      rulesList.innerHTML = '<div class="no-players">' + 'No server rules are currently available.' + '</div>';
    }

    /*
     * Last update time.
     */
    const updatedDate = new Date(data.updated);
    document .getElementById("updatedTime").textContent = "Server data updated: " + updatedDate.toLocaleString();
  }catch(error){
    /*
     * Server appears offline or unreachable.
     */
    console.error("Could not load server data:", error);
    document.getElementById("statusDot").className = "status-dot offline";
    document.getElementById("serverStatus").textContent = "SERVER STATUS UNAVAILABLE";
    document.getElementById("playerList").innerHTML = '<span class="no-players">' + 'Could not contact the server.' + '</span>';
  }
}

/*
 * Load immediately.
 */
loadServerData();

/*
 * Refresh every 60 seconds.
 */
setInterval(loadServerData, 60000);